/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.SaleJpaController;
import entity.Sale;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JTable;

/**
 *
 * @author magic
 */
public class DP2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private EntityManagerFactory emf;
    
    public DP2() {
        initComponents();
        emf = Persistence.createEntityManagerFactory("DP2PU");
        saleSearchPanel.setVisible(false);
        allSalePanel.setVisible(false);
        addSalePanel.setVisible(false);
        displaySalePanel.setVisible(false);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saleSearchPanel = new javax.swing.JPanel();
        txtSaleSearch = new javax.swing.JTextField();
        btnSaleSearch = new javax.swing.JButton();
        lblSaleId = new javax.swing.JLabel();
        btnClearSaleSearch = new javax.swing.JButton();
        lblSaleSearch = new javax.swing.JLabel();
        btnSaleSearchBack = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        lblMain = new javax.swing.JLabel();
        btnAddSaleRecod = new javax.swing.JButton();
        btnMonthlyReport = new javax.swing.JButton();
        btnWeeklyReport = new javax.swing.JButton();
        btnSaleSearchPanel = new javax.swing.JButton();
        GetAllSales = new javax.swing.JButton();
        allSalePanel = new javax.swing.JPanel();
        allSaleScrollPane = new javax.swing.JScrollPane();
        allSaleBack = new javax.swing.JButton();
        addSalePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtAddSaleId = new javax.swing.JTextField();
        txtAddProductId = new javax.swing.JTextField();
        txtAddSaleQty = new javax.swing.JTextField();
        txtAddSaleCost = new javax.swing.JTextField();
        txtAddSaleDate = new javax.swing.JTextField();
        btnAddSale = new javax.swing.JButton();
        btnAddSaleClear = new javax.swing.JButton();
        btnAddSaleBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        displaySalePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtDisplaySaleId = new javax.swing.JTextField();
        txtDisplayProductId = new javax.swing.JTextField();
        txtDisplaySaleQty = new javax.swing.JTextField();
        txtDisplaySaleCost = new javax.swing.JTextField();
        txtDisplaySaleDate = new javax.swing.JTextField();
        btnEditSaveSale = new javax.swing.JButton();
        btnCancelSaveSale = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSaleSearch.setText("Search");
        btnSaleSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleSearchActionPerformed(evt);
            }
        });

        lblSaleId.setText("Sale ID");

        btnClearSaleSearch.setText("Clear");

        lblSaleSearch.setText("SALE RECORD SEARCH");

        btnSaleSearchBack.setText("Back");
        btnSaleSearchBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleSearchBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saleSearchPanelLayout = new javax.swing.GroupLayout(saleSearchPanel);
        saleSearchPanel.setLayout(saleSearchPanelLayout);
        saleSearchPanelLayout.setHorizontalGroup(
            saleSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saleSearchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSaleId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(saleSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaleSearch)
                    .addComponent(txtSaleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(saleSearchPanelLayout.createSequentialGroup()
                        .addComponent(btnSaleSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearSaleSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaleSearchBack)))
                .addGap(72, 72, 72))
        );
        saleSearchPanelLayout.setVerticalGroup(
            saleSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saleSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSaleSearch)
                .addGap(23, 23, 23)
                .addGroup(saleSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaleId))
                .addGap(18, 18, 18)
                .addGroup(saleSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaleSearch)
                    .addComponent(btnClearSaleSearch)
                    .addComponent(btnSaleSearchBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblMain.setText("PEOPLE HEALTH PHARMACY");

        btnAddSaleRecod.setText("Add Sales Record");
        btnAddSaleRecod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSaleRecodActionPerformed(evt);
            }
        });

        btnMonthlyReport.setText("Monthly Sale Report");

        btnWeeklyReport.setText("Weekly Sales Report");

        btnSaleSearchPanel.setText("Sale Search");
        btnSaleSearchPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleSearchPanelActionPerformed(evt);
            }
        });

        GetAllSales.setText("Get All Sales");
        GetAllSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetAllSalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMain)
                .addGap(96, 96, 96))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddSaleRecod)
                            .addComponent(btnWeeklyReport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMonthlyReport, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSaleSearchPanel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(GetAllSales)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMain)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSaleRecod)
                    .addComponent(btnMonthlyReport))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWeeklyReport)
                    .addComponent(btnSaleSearchPanel))
                .addGap(18, 18, 18)
                .addComponent(GetAllSales)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        allSaleBack.setText("Back");
        allSaleBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSaleBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout allSalePanelLayout = new javax.swing.GroupLayout(allSalePanel);
        allSalePanel.setLayout(allSalePanelLayout);
        allSalePanelLayout.setHorizontalGroup(
            allSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allSalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allSaleScrollPane)
                .addContainerGap())
            .addGroup(allSalePanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(allSaleBack)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        allSalePanelLayout.setVerticalGroup(
            allSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allSalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allSaleScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allSaleBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("ADD SALE RECORD");

        btnAddSale.setText("Add");

        btnAddSaleClear.setText("Clear");

        btnAddSaleBack.setText("Back");
        btnAddSaleBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSaleBackActionPerformed(evt);
            }
        });

        jLabel8.setText("Sale ID");

        jLabel9.setText("Product ID");

        jLabel10.setText("Qty");

        jLabel11.setText("Cost");

        jLabel12.setText("Date");

        javax.swing.GroupLayout addSalePanelLayout = new javax.swing.GroupLayout(addSalePanel);
        addSalePanel.setLayout(addSalePanelLayout);
        addSalePanelLayout.setHorizontalGroup(
            addSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSalePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(addSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(btnAddSale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addSalePanelLayout.createSequentialGroup()
                        .addComponent(btnAddSaleClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddSaleBack))
                    .addComponent(jLabel7)
                    .addComponent(txtAddSaleId)
                    .addComponent(txtAddProductId)
                    .addComponent(txtAddSaleQty)
                    .addComponent(txtAddSaleCost)
                    .addComponent(txtAddSaleDate))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        addSalePanelLayout.setVerticalGroup(
            addSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(addSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddSaleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddSaleQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddSaleCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddSaleDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSale)
                    .addComponent(btnAddSaleClear)
                    .addComponent(btnAddSaleBack))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel13.setText("SALE RECORD");

        txtDisplaySaleId.setEditable(false);

        txtDisplayProductId.setEditable(false);

        txtDisplaySaleQty.setEditable(false);

        txtDisplaySaleCost.setEditable(false);

        txtDisplaySaleDate.setEditable(false);

        btnEditSaveSale.setText("Edit");
        btnEditSaveSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSaveSaleActionPerformed(evt);
            }
        });

        btnCancelSaveSale.setText("Cancel");
        btnCancelSaveSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelSaveSaleActionPerformed(evt);
            }
        });

        jLabel14.setText("Sale ID");

        jLabel15.setText("Product ID");

        jLabel16.setText("Qty");

        jLabel17.setText("Cost");

        jLabel18.setText("Date");

        javax.swing.GroupLayout displaySalePanelLayout = new javax.swing.GroupLayout(displaySalePanel);
        displaySalePanel.setLayout(displaySalePanelLayout);
        displaySalePanelLayout.setHorizontalGroup(
            displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displaySalePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13)
                        .addComponent(txtDisplaySaleId, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(txtDisplayProductId)
                        .addComponent(txtDisplaySaleQty)
                        .addComponent(txtDisplaySaleCost)
                        .addComponent(txtDisplaySaleDate))
                    .addGroup(displaySalePanelLayout.createSequentialGroup()
                        .addComponent(btnEditSaveSale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelSaveSale)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        displaySalePanelLayout.setVerticalGroup(
            displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displaySalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisplaySaleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisplayProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisplaySaleQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisplaySaleCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisplaySaleDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(displaySalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditSaveSale)
                    .addComponent(btnCancelSaveSale))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saleSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addSalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(displaySalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(allSalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displaySalePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addSalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saleSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(allSalePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaleSearchPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleSearchPanelActionPerformed
        mainPanel.setVisible(false);
        saleSearchPanel.setVisible(true);
    }//GEN-LAST:event_btnSaleSearchPanelActionPerformed

    private void GetAllSalesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GetAllSalesActionPerformed
    {//GEN-HEADEREND:event_GetAllSalesActionPerformed
        // TODO add your handling code here:
        mainPanel.setVisible(false);
        allSalePanel.setVisible(true);
        SaleJpaController saleController = new SaleJpaController(emf);
        List<Sale> results = saleController.findSaleEntities();
        List<String[]> data = new ArrayList<>();
        String[] columnNames = {"Sales ID", "Product ID", "Qty", "Cost", "SaleDate"};
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (Sale sale : results) {
            data.add(new String[] {
                sale.getSalePK().getSaleId() + "",
                sale.getSalePK().getProdId() + "",
                sale.getSaleQty() + "",
                sale.getSalePrice() + "",
                sdf.format(sale.getSaleDate()) + ""
            });
        }
        JTable allSaleTable = new JTable(data.toArray(new Object[][]{}), columnNames);
        allSaleScrollPane.getViewport().add(allSaleTable);
    }//GEN-LAST:event_GetAllSalesActionPerformed

    private void allSaleBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_allSaleBackActionPerformed
    {//GEN-HEADEREND:event_allSaleBackActionPerformed
        // TODO add your handling code here:
        mainPanel.setVisible(true);
        allSalePanel.setVisible(false);
    }//GEN-LAST:event_allSaleBackActionPerformed

    private void btnSaleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleSearchActionPerformed
        saleSearchPanel.setVisible(false);
        displaySalePanel.setVisible(true);
    }//GEN-LAST:event_btnSaleSearchActionPerformed

    private void btnSaleSearchBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleSearchBackActionPerformed
        mainPanel.setVisible(true);
        saleSearchPanel.setVisible(false);
    }//GEN-LAST:event_btnSaleSearchBackActionPerformed

    private void btnAddSaleBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSaleBackActionPerformed
        mainPanel.setVisible(true);
        addSalePanel.setVisible(false);
    }//GEN-LAST:event_btnAddSaleBackActionPerformed

    private void btnAddSaleRecodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSaleRecodActionPerformed
        addSalePanel.setVisible(true);
        mainPanel.setVisible(false);
    }//GEN-LAST:event_btnAddSaleRecodActionPerformed

    private void btnCancelSaveSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelSaveSaleActionPerformed
        saleSearchPanel.setVisible(true);
        displaySalePanel.setVisible(false);
        btnEditSaveSale.setText("Edit");
        txtDisplaySaleId.setEditable(false);
        txtDisplayProductId.setEditable(false);
        txtDisplaySaleQty.setEditable(false);
        txtDisplaySaleCost.setEditable(false);
        txtDisplaySaleDate.setEditable(false);
    }//GEN-LAST:event_btnCancelSaveSaleActionPerformed

    private void btnEditSaveSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSaveSaleActionPerformed
        String status = btnEditSaveSale.getText();
        if (status.equals("Edit")) {
            btnEditSaveSale.setText("Save");
            txtDisplaySaleId.setEditable(true);
            txtDisplayProductId.setEditable(true);
            txtDisplaySaleQty.setEditable(true);
            txtDisplaySaleCost.setEditable(true);
            txtDisplaySaleDate.setEditable(true); 
        }
    }//GEN-LAST:event_btnEditSaveSaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DP2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetAllSales;
    private javax.swing.JPanel addSalePanel;
    private javax.swing.JButton allSaleBack;
    private javax.swing.JPanel allSalePanel;
    private javax.swing.JScrollPane allSaleScrollPane;
    private javax.swing.JButton btnAddSale;
    private javax.swing.JButton btnAddSaleBack;
    private javax.swing.JButton btnAddSaleClear;
    private javax.swing.JButton btnAddSaleRecod;
    private javax.swing.JButton btnCancelSaveSale;
    private javax.swing.JButton btnClearSaleSearch;
    private javax.swing.JButton btnEditSaveSale;
    private javax.swing.JButton btnMonthlyReport;
    private javax.swing.JButton btnSaleSearch;
    private javax.swing.JButton btnSaleSearchBack;
    private javax.swing.JButton btnSaleSearchPanel;
    private javax.swing.JButton btnWeeklyReport;
    private javax.swing.JPanel displaySalePanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblSaleId;
    private javax.swing.JLabel lblSaleSearch;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel saleSearchPanel;
    private javax.swing.JTextField txtAddProductId;
    private javax.swing.JTextField txtAddSaleCost;
    private javax.swing.JTextField txtAddSaleDate;
    private javax.swing.JTextField txtAddSaleId;
    private javax.swing.JTextField txtAddSaleQty;
    private javax.swing.JTextField txtDisplayProductId;
    private javax.swing.JTextField txtDisplaySaleCost;
    private javax.swing.JTextField txtDisplaySaleDate;
    private javax.swing.JTextField txtDisplaySaleId;
    private javax.swing.JTextField txtDisplaySaleQty;
    private javax.swing.JTextField txtSaleSearch;
    // End of variables declaration//GEN-END:variables
}
