/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.SaleJpaController;
import entity.Sale;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JTable;

/**
 *
 * @author magic
 */
public class DP2 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private EntityManagerFactory emf;
    
    public DP2() {
        initComponents();
        emf = Persistence.createEntityManagerFactory("DP2PU");
        SaleSearchPanel.setVisible(false);
        allSalePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        SaleSearchPanel = new javax.swing.JPanel();
        txtSaleSearch = new javax.swing.JTextField();
        btnSaleSearch = new javax.swing.JButton();
        lblSaleId = new javax.swing.JLabel();
        btnClearSaleSearch = new javax.swing.JButton();
        lblSaleSearch = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        lblMain = new javax.swing.JLabel();
        btnAddSaleRecod = new javax.swing.JButton();
        btnMonthlyReport = new javax.swing.JButton();
        btnWeeklyReport = new javax.swing.JButton();
        btnSaleSearchPanel = new javax.swing.JButton();
        GetAllSales = new javax.swing.JButton();
        allSalePanel = new javax.swing.JPanel();
        allSaleScrollPane = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSaleSearch.setText("Search");

        lblSaleId.setText("Sale ID");

        btnClearSaleSearch.setText("Clear");

        lblSaleSearch.setText("SALE RECORD SEARCH");

        javax.swing.GroupLayout SaleSearchPanelLayout = new javax.swing.GroupLayout(SaleSearchPanel);
        SaleSearchPanel.setLayout(SaleSearchPanelLayout);
        SaleSearchPanelLayout.setHorizontalGroup(
            SaleSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SaleSearchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSaleId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SaleSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaleSearch)
                    .addGroup(SaleSearchPanelLayout.createSequentialGroup()
                        .addComponent(btnSaleSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearSaleSearch))
                    .addComponent(txtSaleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
        );
        SaleSearchPanelLayout.setVerticalGroup(
            SaleSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaleSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSaleSearch)
                .addGap(23, 23, 23)
                .addGroup(SaleSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaleId))
                .addGap(18, 18, 18)
                .addGroup(SaleSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaleSearch)
                    .addComponent(btnClearSaleSearch))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        lblMain.setText("PEOPLE HEALTH PHARMACY");

        btnAddSaleRecod.setText("Add Sales Record");

        btnMonthlyReport.setText("Monthly Sale Report");

        btnWeeklyReport.setText("Weekly Sales Report");

        btnSaleSearchPanel.setText("Sale Search");
        btnSaleSearchPanel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaleSearchPanelActionPerformed(evt);
            }
        });

        GetAllSales.setText("Get All Sales");
        GetAllSales.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                GetAllSalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMain)
                .addGap(96, 96, 96))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddSaleRecod)
                            .addComponent(btnWeeklyReport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMonthlyReport)
                            .addComponent(btnSaleSearchPanel)))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(GetAllSales)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMain)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSaleRecod)
                    .addComponent(btnMonthlyReport))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWeeklyReport)
                    .addComponent(btnSaleSearchPanel))
                .addGap(18, 18, 18)
                .addComponent(GetAllSales)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout allSalePanelLayout = new javax.swing.GroupLayout(allSalePanel);
        allSalePanel.setLayout(allSalePanelLayout);
        allSalePanelLayout.setHorizontalGroup(
            allSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allSalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allSaleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        allSalePanelLayout.setVerticalGroup(
            allSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allSalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(allSaleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SaleSearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(allSalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaleSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(allSalePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaleSearchPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleSearchPanelActionPerformed
        MainPanel.setVisible(false);
        SaleSearchPanel.setVisible(true);
    }//GEN-LAST:event_btnSaleSearchPanelActionPerformed

    private void GetAllSalesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GetAllSalesActionPerformed
    {//GEN-HEADEREND:event_GetAllSalesActionPerformed
        // TODO add your handling code here:
        MainPanel.setVisible(false);
        allSalePanel.setVisible(true);
        SaleJpaController saleController = new SaleJpaController(emf);
        List<Sale> results = saleController.findSaleEntities();
        List<String[]> data = new ArrayList<>();
        String[] columnNames = {"Sales ID", "Product ID", "Qty", "Cost", "SaleDate"};
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        for (Sale sale : results) {
            data.add(new String[] {
                sale.getSalePK().getSaleId() + "",
                sale.getSalePK().getProdId() + "",
                sale.getSaleQty() + "",
                sale.getSalePrice() + "",
                sdf.format(sale.getSaleDate()) + ""
            });
        }
        JTable allSaleTable = new JTable(data.toArray(new Object[][]{}), columnNames);
        allSaleScrollPane.getViewport().add(allSaleTable);
    }//GEN-LAST:event_GetAllSalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DP2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetAllSales;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SaleSearchPanel;
    private javax.swing.JPanel allSalePanel;
    private javax.swing.JScrollPane allSaleScrollPane;
    private javax.swing.JButton btnAddSaleRecod;
    private javax.swing.JButton btnClearSaleSearch;
    private javax.swing.JButton btnMonthlyReport;
    private javax.swing.JButton btnSaleSearch;
    private javax.swing.JButton btnSaleSearchPanel;
    private javax.swing.JButton btnWeeklyReport;
    private javax.swing.JLabel lblMain;
    private javax.swing.JLabel lblSaleId;
    private javax.swing.JLabel lblSaleSearch;
    private javax.swing.JTextField txtSaleSearch;
    // End of variables declaration//GEN-END:variables
}
